# Generated by Django 4.2.16 on 2025-06-25 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postimage',
            name='url',
            field=models.CharField(max_length=255),
        ),
    ]
