# Generated by Django 4.2.16 on 2025-07-03 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_alter_postimage_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='image_url',
            field=models.CharField(default='/media/users/default/user.png', max_length=255),
        ),
    ]
