# Generated by Django 4.2.16 on 2025-06-13 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_alter_postimage_options_remove_postimage_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postimage',
            old_name='image_url',
            new_name='url',
        ),
    ]
