# Generated by Django 4.2.16 on 2025-07-09 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_tag_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='운영자가 특별히 지정한 태그 여부'),
        ),
    ]
