# Generated by Django 4.2.16 on 2025-07-12 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_collection_collectionmember'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='collectionmember',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='collectionmember',
            name='collection',
        ),
        migrations.RemoveField(
            model_name='collectionmember',
            name='user',
        ),
        migrations.DeleteModel(
            name='Collection',
        ),
        migrations.DeleteModel(
            name='CollectionMember',
        ),
    ]
