# Generated by Django 4.2.16 on 2025-06-20 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('likes', '0003_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commentlike',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='postlike',
            options={'ordering': ['-created_at']},
        ),
    ]
