version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "<TASK_DEFINITION>"
        LoadBalancerInfo:
          ContainerName: "<CONTAINER_NAME>"
          ContainerPort: 8080
#Hooks:
#  AfterAllowTestTraffic:
#    - location: scripts/health_check.sh
#      timeout: 180
#      runas: root