# Generated by Django 4.2.16 on 2025-06-05 21:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='uid',
            field=models.CharField(db_index=True, default=uuid.uuid4, editable=False, max_length=50, unique=True),
        ),
    ]
