# Generated by Django 4.2.16 on 2025-05-27 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_tag_post_comment_postlike_follow'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
