# Generated by Django 4.2.16 on 2025-06-10 11:38

from django.db import migrations, models
import snapsapi.apps.users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default=snapsapi.apps.users.models.generate_username_with_short_uuid, max_length=50, unique=True),
        ),
    ]
