# Generated by Django 4.2.16 on 2025-06-18 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='deleted',
            new_name='is_deleted',
        ),
    ]
