# Generated by Django 4.2.16 on 2025-05-29 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default='User_qjs_8i2X', max_length=30, unique=True),
        ),
    ]
