# Generated by Django 4.2.16 on 2025-06-07 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default='User_<function generate_short_uuid at 0x102a36520>', max_length=50, unique=True),
        ),
    ]
