# Generated by Django 4.2.16 on 2025-06-02 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default='User_9S0ddZ5t', max_length=30, unique=True),
        ),
    ]
