# Generated by Django 4.2.16 on 2025-06-21 18:12

import django.core.validators
from django.db import migrations, models
import snapsapi.apps.users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_followers_count_user_following_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_username_changed',
            field=models.BooleanField(default=False, help_text='Becomes True if the user has changed their initial username at least once.'),
        ),
        migrations.AddField(
            model_name='user',
            name='username_last_changed_at',
            field=models.DateTimeField(blank=True, help_text='Stores the timestamp of the last username change.', null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default=snapsapi.apps.users.models.generate_username_with_short_uuid, max_length=30, unique=True, validators=[django.core.validators.MinLengthValidator(5)]),
        ),
    ]
