# Generated by Django 4.2.16 on 2025-06-03 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default='User_XcsFF4mB7', max_length=30, unique=True),
        ),
    ]
