# Generated by Django 4.2.16 on 2025-06-03 04:26

from django.db import migrations, models
import snapsapi.apps.users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='uid',
            field=models.CharField(db_index=True, default=snapsapi.apps.users.models.generate_sid, editable=False, help_text='외부 노출용 유저 고유 식별자', max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default='User_40scs8iCp', max_length=30, unique=True),
        ),
    ]
