# Generated by Django 4.2.16 on 2025-07-03 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_user_managers_user_posts_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image_url',
            field=models.CharField(default='/media/users/default/user.png', max_length=255),
        ),
    ]
