# Generated by Django 4.2.16 on 2025-07-18 13:17

import django.core.validators
from django.db import migrations, models
import snapsapi.apps.users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_profile_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default=snapsapi.apps.users.models.generate_username_with_short_uuid, max_length=20, unique=True, validators=[django.core.validators.MinLengthValidator(5), django.core.validators.RegexValidator(code='invalid_username', message='사용자명은 영문소문자, 숫자, 마침표(.), 밑줄(_)만 사용 가능합니다.', regex='^[A-Za-z0-9._]+$')]),
        ),
    ]
